namespace EbaySharp.Entities.Sell.Fulfillment.Order
{
    public enum TaxTypeEnum
    {
        STATE_SALES_TAX, PROVINCE_SALES_TAX, REGION, VAT, GST, ELECTRONIC_RECYCLING_FEE, MATTRESS_RECYCLING_FEE, ADDITIONAL_FEE, BATTERY_RECYCLING_FEE, TIRE_RECYCLING_FEE, WHITE_GOODS_DISPOSABLE_TAX, IMPORT_VAT, SST
    }
}
