name: Build & Test DEV

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build_and_test:
    name: "Build & Test"
    runs-on: windows-latest
    environment: DEV
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    # env:
    #   SLN_FILE: "/home/runner/work/EbaySharp/EbaySharp/EbaySharp.sln"
    
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    # - name: Verify solution Path
    #   run: ls -la $SLN_FILE
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/test-results.trx
  Test_Report:
    name: "Test Report"
    runs-on: windows-latest
    needs: build_and_test
    permissions:
      checks: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: test-results
        path: TestResults/
    - name: Initialize Git (for test-reporter)
      run: |
        git init -q  # Silent init
        git config --global --add safe.directory '*'
    - uses: dorny/test-reporter@v1
      if: success() || failure() # run this step even if previous step failed
      with:
        name: Test Report
        # Name of the check run which will be created
        reporter: dotnet-trx # Format of test results
        list-tests: "all"
        fail-on-error: "false"
        #artifact: test-results
        path: TestResults/test-results.trx # Path to test results (inside artifact .zip)
        path-replace-backslashes: true
