name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Build_and_Test:
    env:
      SLN_FILE: "/home/runner/work/EbaySharp/EbaySharp/EbaySharp.sln"
      REPORTS_PATH: "./test-reports/build_$GITHUB_RUN_ATTEMPT"
      clientId: ${{ secrets.CLIENT_ID }}
      clientSecret: ${{ secrets.CLIENT_SECRET }}
      refreshToken: ${{ secrets.REFRESH_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 #fetch-depth is needed for GitVersion

      - name: Setup .NET
        #Build/pack the project
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Verify solution Path
        run: ls -la $SLN_FILE

      - name: Restore dependencies
        run: dotnet restore $SLN_FILE
      - name: Build
        run: dotnet build --no-restore --configuration Release $SLN_FILE
      # - name: Display secrets
      #   run: |
      #     echo clientId: $clientId
      #     echo clientSecret: $clientSecret
      - name: Test
        run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults" --configuration Release $SLN_FILE
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: EbaySharp Tests # Name of the check run which will be created
          reporter: dotnet-trx # Format of test results
          list-tests: "all"
          fail-on-error: "true"
          #artifact: test-results
          path: ${{ github.workspace }}/TestResults/test-results.trx # Path to test results (inside artifact .zip)
  # TestReport:
  #   steps:
  #     - name: Test
  #       run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults" --configuration Release $SLN_FILE
